import type { OnboardingForm } from "./types";

export const FORM_TEMPLATES: Omit<OnboardingForm, "id" | "createdAt" | "updatedAt">[] = [
  {
    name: "Web Design Project Onboarding",
    description: "Gather requirements for web design projects",
    isTemplate: true,
    fields: [
      {
        id: "company-name",
        type: "text",
        label: "Company Name",
        required: true,
        order: 0,
      },
      {
        id: "contact-name",
        type: "text",
        label: "Contact Person",
        required: true,
        order: 1,
      },
      {
        id: "email",
        type: "email",
        label: "Email Address",
        required: true,
        order: 2,
      },
      {
        id: "phone",
        type: "phone",
        label: "Phone Number",
        required: false,
        order: 3,
      },
      {
        id: "website-type",
        type: "multiple-choice",
        label: "What type of website do you need?",
        required: true,
        options: ["Business Website", "E-commerce", "Portfolio", "Blog", "Landing Page", "Other"],
        order: 4,
      },
      {
        id: "pages",
        type: "text",
        label: "How many pages?",
        placeholder: "e.g., 5-10 pages",
        required: false,
        order: 5,
      },
      {
        id: "features",
        type: "checkboxes",
        label: "Required features:",
        required: false,
        options: ["Contact Form", "Blog", "E-commerce", "User Accounts", "Search", "Analytics", "SEO Optimization"],
        order: 6,
      },
      {
        id: "design-style",
        type: "dropdown",
        label: "Design Style Preference",
        required: false,
        options: ["Modern & Minimalist", "Bold & Creative", "Corporate & Professional", "Fun & Playful", "Elegant & Luxury"],
        order: 7,
      },
      {
        id: "timeline",
        type: "date",
        label: "Desired Launch Date",
        helpText: "When would you like the website to go live?",
        required: false,
        order: 8,
      },
      {
        id: "budget",
        type: "dropdown",
        label: "Budget Range",
        required: false,
        options: ["Under $5,000", "$5,000 - $10,000", "$10,000 - $25,000", "$25,000 - $50,000", "Over $50,000"],
        order: 9,
      },
      {
        id: "existing-assets",
        type: "file-upload",
        label: "Upload existing assets (logo, brand guidelines, images)",
        helpText: "Max 10MB per file",
        required: false,
        order: 10,
      },
      {
        id: "additional-info",
        type: "textarea",
        label: "Additional Information",
        placeholder: "Tell us anything else we should know about your project...",
        required: false,
        order: 11,
      },
    ],
  },
  {
    name: "Branding Package Onboarding",
    description: "Collect details for branding projects",
    isTemplate: true,
    fields: [
      {
        id: "company-name",
        type: "text",
        label: "Company/Brand Name",
        required: true,
        order: 0,
      },
      {
        id: "contact-name",
        type: "text",
        label: "Contact Person",
        required: true,
        order: 1,
      },
      {
        id: "email",
        type: "email",
        label: "Email Address",
        required: true,
        order: 2,
      },
      {
        id: "industry",
        type: "text",
        label: "Industry/Business Type",
        placeholder: "e.g., Technology, Healthcare, Fashion",
        required: true,
        order: 3,
      },
      {
        id: "deliverables",
        type: "checkboxes",
        label: "What do you need?",
        required: true,
        options: ["Logo Design", "Brand Guidelines", "Business Cards", "Social Media Templates", "Website Design", "Marketing Materials"],
        order: 4,
      },
      {
        id: "target-audience",
        type: "textarea",
        label: "Target Audience",
        placeholder: "Describe your ideal customer...",
        required: false,
        order: 5,
      },
      {
        id: "brand-personality",
        type: "checkboxes",
        label: "Brand Personality (select all that apply):",
        required: false,
        options: ["Professional", "Fun", "Trustworthy", "Innovative", "Luxurious", "Eco-friendly", "Bold", "Minimal"],
        order: 6,
      },
      {
        id: "competitors",
        type: "textarea",
        label: "Competitor websites or brands you admire",
        placeholder: "Share URLs or names...",
        required: false,
        order: 7,
      },
      {
        id: "timeline",
        type: "date",
        label: "When do you need this completed?",
        required: false,
        order: 8,
      },
    ],
  },
  {
    name: "General Service Onboarding",
    description: "Simple form for any service",
    isTemplate: true,
    fields: [
      {
        id: "name",
        type: "text",
        label: "Your Name",
        required: true,
        order: 0,
      },
      {
        id: "email",
        type: "email",
        label: "Email Address",
        required: true,
        order: 1,
      },
      {
        id: "company",
        type: "text",
        label: "Company Name",
        required: false,
        order: 2,
      },
      {
        id: "phone",
        type: "phone",
        label: "Phone Number",
        required: false,
        order: 3,
      },
      {
        id: "service-type",
        type: "dropdown",
        label: "Service Type",
        required: true,
        options: ["Design", "Development", "Marketing", "Consulting", "Other"],
        order: 4,
      },
      {
        id: "description",
        type: "textarea",
        label: "Project Description",
        placeholder: "Tell us about your project...",
        required: true,
        order: 5,
      },
      {
        id: "timeline",
        type: "date",
        label: "Preferred Start Date",
        required: false,
        order: 6,
      },
      {
        id: "budget",
        type: "dropdown",
        label: "Budget Range",
        required: false,
        options: ["Under $1,000", "$1,000 - $5,000", "$5,000 - $10,000", "$10,000+", "Flexible"],
        order: 7,
      },
    ],
  },
];
